### ISSUE TITLE
Import from Netflix

### ISSUE THREAD

**Issue by NoelDeMartin** [NoelDeMartin/media-kraken#28]
Looking at [Solidflix](https://github.com/OxfordHCC/solid-media) it seems like it's possible to import movies from Netflix, so it'd be nice to implement that as well.

**Comment by josephguillaume** [comment]
In case it helps, here is my understanding:

Solidflix asks the user to download their viewer history, which is a CSV with titles and watch date.

The uploaded file is split by line, searches are made to tmdb for each title, and the date from CSV is saved as a watch action date.

Import from Netflix file
https://github.com/OxfordHCC/solid-media/blob/b93ea16754fc718e5681ec458a697d5a39cea288/src/components/AddPopup.tsx#L39

Watch and save functions
https://github.com/OxfordHCC/solid-media/blob/b93ea16754fc718e5681ec458a697d5a39cea288/src/components/DiscoverPane.tsx#L836
https://github.com/OxfordHCC/solid-media/blob/b93ea16754fc718e5681ec458a697d5a39cea288/src/components/DiscoverPane.tsx#L474

Search
https://github.com/OxfordHCC/solid-media/blob/b93ea16754fc718e5681ec458a697d5a39cea288/src/media.ts#L91


Data exports from Netflix also include more granular start and end watch times, but are more complex to get.

**Comment by josephguillaume** [comment]
Incidentally, if the data includes a sameAs reference for Netflix, then Media Kraken already provides a link "view at netflix.com", which then opens in the app (on Android at least)

```
<https://schema.org/sameAs> <https://www.netflix.com/au/title/80211726>.
```

https://github.com/NoelDeMartin/media-kraken/blob/26c09436cbf71236fee03c034025750c7769454c/src/components/MovieDetails.vue#L104

**Comment by NoelDeMartin** [comment]
Implemented in [v0.1.19](https://github.com/NoelDeMartin/media-kraken/blob/main/CHANGELOG.md#v0119---2024-12-03)!

I don't actually have a Netflix account, so I couldn't test this with the latest format of their CSV. But I think it should work, I'd appreciate it if someone can test it :).

**Comment by josephguillaume** [comment]
I'm in Australia and it looks like my viewing history is in d/m/y. I don't know if this is locale specific.

Unfortunately it seems at least my browser (Vivaldi on mobile) tries to parse it as m/d/y.

However, other than that I can confirm with a test sample that I successfully imported one movie as watched, had one confirmed as already in my collection, and one correctly ignored as not a movie. The import report is great too. Thanks!

**Comment by NoelDeMartin** [comment]
Thanks for testing @josephguillaume.

I was assuming the dates had a standard format, so I was just using the `Date` constructor, but it seems like that was too naive :/. I tried to find more examples, and indeed I see that sometimes they can be different...

I haven't been able to find any documentation on which formats to expect, and I think it wouldn't be safe to look at the browser locale either. In the end, I've implemented [an algorithm to detect the date format](https://github.com/NoelDeMartin/media-kraken/blob/2389df60e73cd793f51d2188d23ae768dd88fe3e/src/utils/netflix.ts#L97) that is a lot more complicated than it should. I hope it doesn't backfire 😅.

I've released another version, you can check again in v0.1.20.

**Comment by josephguillaume** [comment]
Works for me. Thanks!
It turns out some TV shows don't name the season, so they show up as "This movie could not be found". I'd say that's acceptable.
