### ISSUE TITLE
Support importing movies from goodfil.ms

### ISSUE THREAD

**Issue by gabrielbckr** [NoelDeMartin/media-kraken#6]
goodfil.ms is a movie aggregating service and I would like to import data from this service. It allows users to export with csv format.

**Comment by NoelDeMartin** [comment]
Hi there, thanks for opening the request!

I'll look into this and it'll probably be included in the next release, but I've been doing some initial tests and I've seen a couple of problems with that csv.

The first problem is that it doesn't include an id to a 3rd party service. For example, an `imdb.com` url or even the `goofil.ms` url. This means that I'll have to use the title of the movie to search a match. A movie title is not unique, multiple movies have the same title, so I'll have to use the release year as well. An additional problem with this is that the title can be different in other languages, it seems to use the english title but I can't guarantee that media-kraken will always use the english title (this is actually something I will probably change in the near future). So it may difficult to find the match for some movies, in any case you should be able to see this while importing and do it manually for the ones that don't match.

A second problem is that I'm not sure what movies are included in that csv. It seems like it only includes films that have been in "your queue" at some point (a term used by the website). This means movies removed from the queue appear in the csv as well, and I'm not sure if that means that you've watched the movies (so they should be imported as "watched" in media kraken) or you don't want them in your collection. I'll probably have a couple of checkboxes to configure this behaviour. But movies that are in other lists will not be included in the csv. Nothing I can do about that.

**Comment by gabrielbckr** [comment]
Thanks for the reply. 

I am aware of the difficulties faced to integrate movie-kraken with goodfil.ms and probabily it's not prioritary once there are many other services with much more users. For now, any instruction to make a json compatible with movie-kraken from this csv would be awesome. 

I'm very pleased to know that such services are being developed over solid. Thanks for the job!

**Comment by NoelDeMartin** [comment]
It's ok, I don't think it'll take me long to implement this :). I'm also interested in exploring what formats other services use and what people is importing so it's fine. If the import dialog grows out of hand, I'll probably refactor it.

> Any instruction to make a json compatible with movie-kraken from this csv would be awesome.

You can always implement a script unrelated to media-kraken that parses the csv an generates a JSON-LD using the proper types documented [here](https://github.com/NoelDeMartin/media-kraken/tree/main/docs#data-schema). If you are not familiar with semantic data, you can get an example json by using media-kraken with browser storage, adding a couple of movies, and exporting the collection.

This shouldn't be difficult for developers, but I'm trying to make the app non-developer friendly :). It's also true that using the import tool it's easier to get better data using the TMDB api to get things such as the movie poster.

**Comment by NoelDeMartin** [comment]
This has been implemented in the [0.1.4 release](https://github.com/NoelDeMartin/media-kraken/releases/tag/v0.1.4), let me know if you've got any problems :).

In the end I didn't implement importing watched movies given the ambiguity I mentioned a couple of comments ago, so you'll have to mark then manually.
